### ISSUE TITLE
Application not launching on Fedora workstation 39

### ISSUE THREAD

**Issue by ispanos** [flathub/net.corluma.Corluma#10]
I'm running Gnome on Fedora 39 and wayland 
```
~ flatpak run net.corluma.Corluma     
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, xcb.

~ flatpak run --command=bash --devel net.corluma.Corluma
error: runtime/org.kde.Sdk/x86_64/6.5 not installed
```

I also tied the following, but the error was the same.
```
~flatpak run net.corluma.Corluma -env="LANG=C.UTF-8" -env="QT_QPA_PLATFORM=xcb"  
```

**Comment by timsee** [comment]
Interesting, I think the relevant error is here:

`error: runtime/org.kde.Sdk/x86_64/6.5 not installed`

Thats the [runtime](https://github.com/flathub/net.corluma.Corluma/blob/master/net.corluma.Corluma.yml#L3) used by the application. I would expect that to be installed automatically (see [here](https://docs.flatpak.org/en/latest/basic-concepts.html#runtimes) for more information), but can you try `flatpak repair` or explicitly installing it, IE: `flatpak install flathub  org.Kde.Platform//6.5`

**Comment by ispanos** [comment]
Hello,

Thanks for the reply.  I think `error: runtime/org.kde.Sdk/x86_64/6.5 not installed` is only relevant to why I can't use `--devel`, beause `org.Kde.Platform` is installed. I uninstalled corluma last time, so bellow you can see the installation process. The error persists. 

```
flatpak install net.corluma.Corluma

Looking for matches…
Required runtime for net.corluma.Corluma/x86_64/stable (runtime/org.kde.Platform/x86_64/6.5) found in remote flathub
Do you want to install it? [Y/n]: y

net.corluma.Corluma permissions:
    ipc      network      fallback-x11      wayland      x11     file access [1]     dbus access [2]

    [1] xdg-config/kdeglobals:ro, xdg-documents
    [2] com.canonical.AppMenu.Registrar


        ID                                                               Branch              Op             Remote              Download
 1. [✓] org.kde.Platform.Locale                                          6.5                 i              flathub              17.9 kB / 333.4 MB
 2. [✓] org.kde.PlatformTheme.QGnomePlatform                             6.5                 i              flathub               9.7 MB / 9.7 MB
 3. [✓] org.kde.WaylandDecoration.QAdwaitaDecorations                    6.5                 i              flathub               1.2 MB / 1.2 MB
 4. [✓] org.kde.WaylandDecoration.QGnomePlatform-decoration              6.5                 i              flathub              10.3 MB / 10.3 MB
 5. [✓] org.kde.Platform                                                 6.5                 i              flathub             126.7 MB / 263.1 MB
 6. [✓] net.corluma.Corluma                                              stable              i              flathub              17.6 MB / 17.7 MB

Installation complete.
---

flatpak run net.corluma.Corluma    

Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, xcb.


flatpak install flathub org.kde.Platform 
Looking for matches…
Similar refs found for ‘org.kde.Platform’ in remote ‘flathub’ (system):

   1) runtime/org.kde.Platform/x86_64/5.10
   2) runtime/org.kde.Platform/x86_64/5.12
   3) runtime/org.kde.Platform/x86_64/5.13
   4) runtime/org.kde.Platform/x86_64/5.11
   5) runtime/org.kde.Platform/x86_64/5.14
   6) runtime/org.kde.Platform/x86_64/5.15
   7) runtime/org.kde.Platform/x86_64/5.15-21.08
   8) runtime/org.kde.Platform/x86_64/5.15-22.08
   9) runtime/org.kde.Platform/x86_64/5.15-23.08
  10) runtime/org.kde.Platform/x86_64/6.2
  11) runtime/org.kde.Platform/x86_64/6.3
  12) runtime/org.kde.Platform/x86_64/6.4
  13) runtime/org.kde.Platform/x86_64/6.5
  14) runtime/org.kde.Platform/x86_64/6.6
  15) runtime/org.kde.Platform/x86_64/5.9

Which do you want to use (0 to abort)? [0-15]: 13
Skipping: org.kde.Platform/x86_64/6.5 is already installed

```

**Comment by timsee** [comment]
Hello! could you try the latest version of the app (v1.00.10)? There has been a couple of changes:

1. Qt is now compiled with `-no-bundled-xcb-xinput`, which should force using the system version of the `xcb` instead of trying to run it as a plugin.
2. It is now using a different runtime (6.6).

I think the change to xcb-input should address your issue.

**Comment by hfiguiere** [comment]
I doubt.

This
```
  - --socket=fallback-x11
  - --socket=wayland
```

tells that there is no X11 if it's a Wayland session, and apparently this build only want to use `xcb` qpa, which mean X11 only.

BTW if you build Qt, why do you use the KDE runtime?

**Comment by hfiguiere** [comment]
This seem to match https://github.com/flathub/flathub/pull/4262#discussion_r1241945109

That was on the original submission review. But you reverted it on https://github.com/flathub/net.corluma.Corluma/commit/e040c26fcec93589d0aaaceb350b9d82aee0aeb1

**Comment by timsee** [comment]
Ah, good catch!

> BTW if you build Qt, why do you use the KDE runtime?

Good question, static builds were a holdover from before linux builds were distributed with flathub. Now its hurting the app though, as builds take longer and its creating cases like this issue.

[v1.00.18](https://github.com/flathub/net.corluma.Corluma/pull/16) removes the static builds in favor of linking to Qt in the KDE runtime, which uses wayland now.

**Comment by timsee** [comment]
Ok, issue has been tested in a Fedora Workstation 39 virtual machine and confirmed to be resolved in recent updates.


v1.00.18 loads fine, can use Wayland, and now links to Qt. This is the preferred solution.


v1.00.10 and v1.00.17 both also worked, but still threw a warning during startup, and still forced X11:
``` 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
```


The build from when this issue was created, v0.39.11, is confirmed to crash. It crashed with:
```
flatpak run net.corluma.Corluma
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, xcb.
```


Thanks for your help @hfiguiere, will close out this issue once v1.00.18 is merged and live.
